spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: Abcd123!
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF"

server:
  servlet:
    context-path: /kdt

kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - default
  description: |-
    line 1 hello world
    line 2 xxxx
    line 3

logging:
  level:
    root: info

